### PR TITLE
Release/1.0.9

### PR DESCRIPTION
**Pull request by niall-byrne**
Production release for review.

### CODE REVIEW

**Comment by briandoconnor** [comment]
Some comments related to the readme:
- what is in s3://oicr.docker.private.images/store-and-forward.tar and why is it not versioned?
- s3cmd is not a good tool, you should use the AWS command line tool. S3cmd will work but it will fail on large file transfers (Ubuntu has a very old version in apt-get last I checked)
- the URL in your readme is out of date: "s3cmd get s3://oicr.workflow.bundles/released-bundles/Workflow_Bundle_StoreAndForward_1.0.3_SeqWare_1.1.0.zip"  Needs to be updated to 1.0.9
- https://github.com/ICGC-TCGA-PanCancer/store-and-forward-workflow/blob/release/1.0.9/src/main/java/io/seqware/pancancer/StoreAndForward.java#L317 ... what happens if the upload to S3 fails?  You never catch that so this step would appear to work even if the upload of S3 logs fails.
- https://github.com/ICGC-TCGA-PanCancer/store-and-forward-workflow/blob/release/1.0.9/src/main/java/io/seqware/pancancer/StoreAndForward.java#L335 You pass around secret keys and this will appear in logs.  Not good.  Why not use the AWS key the launcher passes to the worker nodes?

**Comment by briandoconnor** [comment]
The https://github.com/ICGC-TCGA-PanCancer/store-and-forward-workflow/blob/release/1.0.9/workflow/config/StoreAndForward.ini template is missing collabLogKey

**Comment by briandoconnor** [comment]
For s3cmd go ahead and switch to a config file instead of keys on the command line:

```
-c FILE, --config=FILE
                    Config file name. Defaults to /home/mludvig/.s3cfg
```

See http://s3tools.org/usage

Coordinate with Cecile so she gets this file (put it in your tar?).  And in the default INI make sure you put a new variable there that points to ~/.gnos/s3cfg by default.  And have Cecile use this path too.  That should cause minimal disruption but allow you to remove the key/secret key from the INI file

**Comment by briandoconnor** [comment]
pass in the token via a file vai the tar bundle and use backticks in your call to the docker that does the upload.

**Comment by briandoconnor** [comment]
Need to version the following in the worklfow:

   collabDockerName=icgc/cli:latest

Also, you need to move workflow.ini to the right place.

**Comment by briandoconnor** [comment]
collabHost=ec2-52-2-45-147.compute-1.amazonaws.com

That is now an actual host name, see Bob/Andy/Cecile for correct value.

**Comment by briandoconnor** [comment]
Cleanup items that aren't used in the INI ie. coresAddressible

**Comment by denis-yuen** [comment]
Also, if you missed it elsewhere, please use helpful commit messages.
It makes tracing when a feature/bug started or writing release notes much easier.

**Comment by niall-byrne** [comment]
Tests clean after the above commit.
(I make commits, to migrate code changes to my test environment, that's why there are 4 instead of one.)  Please have another look.

**Comment by niall-byrne** [comment]
The changes have been tested, and deployed to cluster 2.  Please have another look.

**Pull request merged**
