### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by cphl**
Comment!

### CODE REVIEW

**Comment by cphl** [comment]
Please don't close. Still a work in progress. More docs on how to upgrade to new versions of workflow, and how to change config to come.
@niall-byrne @briandoconnor Have a look at what is here so far.

**Comment by cphl** [comment]
@denis-yuen @oicr-vchung check out handling failure and other docs to come. Please modify at will.

**Comment by denis-yuen** [comment]
:+1:  Looks good so far. Fixed a few formatting issues. Note that in Markdown, underscores are used for emphasis https://daringfireball.net/projects/markdown/syntax#em so GitHub can get pretty confused the underscore is accidentally used in the middle of a file name, command, etc. Escape it with a "\"

**Comment by denis-yuen** [comment]
FYI, merging this. This is all documentation (as the name implies) so there's no real conflict with 1.0.9 that could arise.

**Pull request merged**
